### ISSUE TITLE
`pg` library seems to be part of source code

### ISSUE THREAD

**Issue by Lewiscowles1986** [vertica/vertica-nodejs#88]
Hi, I Just noticed I got a badge from this, even though we've never collaborated or been in contact.

This looks like it wholesale brings in brianc/node-postgres library in a very strange way (commits, rather than using package.json).

Not only is this a development burden (you'll need to manage backports etc), but it's not exactly clear what this does differently, in a good way, with commits such as: (totally ignoring bizare renaming of ssl to tls, changing copyright notices etc)

- https://github.com/vertica/vertica-nodejs/commit/0db0b33c2a21ba30f8849f1c00485460ba33f2d8
- https://github.com/vertica/vertica-nodejs/commit/9999867c8be146a8917da06e0580162918f9caa1

What is this, if not a nodeJS postgres library?

**Comment by DMickens** [comment]
Vertica in it's beginning was a postgres derived database. It has since branched off enough that a client designed for postgres will not be compatible. Similarly, as you noticed, vertica-nodejs is node-postgres derived. It was originally a node-postgres fork but for visibility reasons was moved to a new repository duplicated and brought in through commits. So is it a nodeJS postgres library? Well, not anymore. I don't know how github badges work, but I assume it would have to be based on commit history. It may be that removing the commit history associated with node-postgres will resolve the issue. I can look into this. Apologies for any inconvenience.
